[%
    T = {
        configure_1                                 = "IntranetUserJS: Alphabetize/prioritize advanced search languages Configuration",
        configure_2                                 = "Home",
        configure_3                                 = "Plugins",
        configure_4                                 = "&rsaquo; IntranetUserJS: Alphabetize/prioritize advanced search languages &rsaquo; Configuration",
        configure_5                                 = "Prioritize Sami (smn, sme, sms, 1 = prioritize, 0 = do not prioritize):",
        configure_6                                 = "Save configuration",
        configure_7                                 = "Upgrade status",
        configure_8                                 = "Plugin has never been upgraded.",
        viewjs_1                                    = "IntranetUserJS: Alphabetize/prioritize advanced search languages",
        viewjs_2                                    = "&rsaquo; AlphabetizeLangAdvSearch &rsaquo; View JS Tool",
    }
%]