[%
    T = {
        configure_1  = "IntranetUserJS: Aakkosta/priorisoi tarkemman haun kielet -asetukset",
        configure_2  = "Etusivu",
        configure_3  = "Liitännäiset",
        configure_4  = "&rsaquo; IntranetUserJS: Aakkosta/priorisoi tarkemman haun kielet &rsaquo; Asetukset",
        configure_5  = "Priorisoi saame (smn, sme, sms, 1 = priorisoi, 0 = älä priorisoi):",
        configure_6  = "Tallenna asetukset",
        configure_7  = "Päivityksen tila",
        configure_8  = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1     = "IntranetUserJS: Aakkosta/priorisoi tarkemman haun kielet",
        viewjs_2     = "&rsaquo; AlphabetizeLangAdvSearch &rsaquo; Näytä JS-työkalu",
    }
%]