[%
    T = {
        configure_1                                 = "IntranetUserJS: Konfiguration för bokstavsordna/prioritera språk i avancerad sökning",
        configure_2                                 = "Hem",
        configure_3                                 = "Plugins",
        configure_4                                 = "&rsaquo; IntranetUserJS: Bokstavsordna/prioritera språk i avancerad sökning &rsaquo; Konfiguration",
        configure_5                                 = "Prioritera samiska (smn, sme, sms, 1 = prioritera, 0 = prioritera inte):",
        configure_6                                 = "Spara konfiguration",
        configure_7                                 = "Uppgraderingsstatus",
        configure_8                                 = "Pluginen har aldrig uppgraderats.",
        viewjs_1                                    = "IntranetUserJS: Bokstavsordna/prioritera språk i avancerad sökning",
        viewjs_2                                    = "&rsaquo; AlphabetizeLangAdvSearch &rsaquo; Visa JS-verktyg",
    }
%]