[%
    T = {
        configure_1                                = "IntranetUserJS: Alphabetize/prioritize advanced search languages Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Alphabetize/prioritize advanced search languages &rsaquo; Konfiguration",
        configure_5                                = "Prioritera samiska (smn, sme, sms, 1 = prioritera, 0 = prioritera inte):",
        configure_6                                = "Spara konfiguration",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Plugin-modulen on aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Alphabetize/prioritize advanced search languages",
        viewjs_2                                   = "&rsaquo; AlphabetizeLangAdvSearch &rsaquo; Visa JS-verktyg",
    }
%]